//
//  CreateOrderModels.swift
//  CleanStore
//
//  Created by Carlos Cortés Sánchez on 11/09/2017.
//  Copyright (c) 2017 Carlos Cortés Sánchez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CreateOrder
{
  // MARK: Use cases
  
  enum FormatExpirationDate
  {
    struct Request
    {
        var date: Date
    }
    struct Response
    {
        var date: Date
    }
    struct ViewModel
    {
        var date: String
    }
  }
}
