//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Carlos Cortés Sánchez on 12/09/2017.
//  Copyright (c) 2017 Carlos Cortés Sánchez. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
    //func doSomething(request: ListOrders.Something.Request)
    func fetchOrders(request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore
{
    //var name: String { get set }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
    var presenter: ListOrdersPresentationLogic?
    var worker: ListOrdersWorker?
    //var name: String = ""
    
    // MARK: Fetch orders
    
    func fetchOrders(request: ListOrders.FetchOrders.Request) {
    }
}
